# Generated by Django 5.0.1 on 2024-05-02 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileListingDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2024, 5, 2, 14, 0, 25, 334959))),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
